tasks:
  - source: tasks/load.py
    product:
      nb: output/load.ipynb
      data: output/data.csv

  - source: tasks/clean.py
    product:
      nb: output/clean.ipynb
      data: output/clean.csv

  - source: tasks/plot.py
    product: output/plot.ipynb
